# Generated by Django 5.1.2 on 2024-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_tweet_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Data de Atualização'),
        ),
    ]
