# Generated by Django 5.1.2 on 2024-10-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
    ]
