# Generated by Django 5.1.2 on 2024-10-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Followers'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='following_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Following'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
    ]
