# Generated by Django 5.1.2 on 2024-10-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='following_count',
        ),
    ]
